
logging:
  config: classpath:logback-boot.xml


spring:
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: xu123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 20000

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml

jwtproperties:
  secret: "fasdgRbsdTjkhDfqskdfngkjdfnskghkerh4532tk34k65b43hj56b34wuikeh123"
  tokenValidityInMilliseconds: 100
  tokenValidityInMillisecondsForRememberMe: 200